apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: sensor-management-ui
    app.kubernetes.io/component: sensor-management-ui
    app.kubernetes.io/instance: sensor-management-ui
  name: sensor-management-ui
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sensor-management-ui:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: services/sensor-management-ui
    git:
      uri: https://github.com/RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-nodejs-nginx:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: MqkP-Uho_Vp8mJVTXoNk
    type: GitHub
  - generic:
      secret: MCTAhhVC2XYilFtMu9ts
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: quay.io/evanshortiss/s2i-nodejs-nginx@sha256:3046843d4fed6a84dcbb3f5a8d8009afa4d1102392257dc1dfe53ea51a171281
    type: ImageChange
