apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: updates-connector
  labels:
    strimzi.io/cluster: iot-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.postgresql.PostgresConnector"
    database.hostname: "iot-psql"
    database.port: "5432"
    database.user: "rhtr-user"
    database.password: "rhtr-pass"
    database.dbname: "city-info"
    database.server.name: "city-info.updates"
    database.whitelist: city-info
    table.whitelist: "meter_update,junction_update"
    database.history.kafka.bootstrap.servers: "iot-cluster-kafka-bootstrap:9093"
    database.history.kafka.topic: "city-info.updates.dbhistory"
