apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-09-11T12:02:35Z"
  labels:
    app: iot-sse-server
    app.kubernetes.io/component: iot-sse-server
    app.kubernetes.io/instance: iot-sse-server
    app.kubernetes.io/name: ""
    app.kubernetes.io/part-of: iot-sse-server
    app.openshift.io/runtime: ""
    app.openshift.io/runtime-version: latest
  name: iot-sse-server
spec:
  clusterIP: 172.30.115.188
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: iot-sse-server
    deploymentconfig: iot-sse-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
