version: '3'
services:
  iot-psql:
    networks: 
      - rhtr-lab
    container_name: iot-lab-psql
    build:
      context: postgresql/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  iot-data-generator:
    networks: 
      - rhtr-lab
    container_name: iot-lab-data-generator
    build:
      context: iot-data-generator/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment: 
      - HTTP_PORT=8082
      - PSQL_CONNECTION_STRING=psql://rhtr-user:rhtr-pass@iot-psql:5432/
  iot-graphql-api:
    depends_on:
      - iot-psql
    networks: 
      - rhtr-lab
    container_name: iot-lab-graphql-api
    build:
      context: iot-graphql-api/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment: 
      - HTTP_PORT=8081
      - DB_CLIENT=pg
      - DB_USER=rhtr-user
      - DB_PASSWORD=rhtr-pass
      - DB_DATABASE=city-info
      - DB_HOST=iot-psql
      - DB_PORT=5432
  iot-sensor-management-ui:
    networks: 
      - rhtr-lab
    container_name: iot-lab-sensor-management-ui
    build:
      context: sensor-management-ui/
      dockerfile: Dockerfile
      args: 
        - IOT_GRAPHQL_HOST=http://localhost:8081/graphql
    ports:
      - "8080:8080"
networks:
  rhtr-lab:
    external: true