apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: iot-psql
  labels:
    app: iot-psql
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/component: iot-psql
    app.kubernetes.io/instance: iot-psql
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - iot-psql
        from:
          kind: ImageStreamTag
          name: 'iot-psql:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: iot-psql
    deploymentconfig: iot-psql
  template:
    metadata:
      labels:
        app: iot-psql
        deploymentconfig: iot-psql
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: iot-psql-data
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: iot-psql
          env:
            - name: PGDATA
              value: /data/data
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: pg-login
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: pg-login
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-data
              mountPath: /data
          terminationMessagePolicy: File
          image: >-
            quay.io/evanshortiss/rhtr-2020-pgsql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
