kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iot-psql-data
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
