apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-psql
    app.kubernetes.io/component: iot-psql
    app.kubernetes.io/instance: iot-psql
    app.openshift.io/runtime-version: latest
  name: iot-psql
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: iot-psql
    deploymentconfig: iot-psql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
