version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rhtr-pass
      POSTGRES_USER: rhtr-user
      POSTGRES_DB: city-info
