apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: iot-data-generator
    app.kubernetes.io/component: iot-data-generator
    app.kubernetes.io/instance: iot-data-generator
    app.kubernetes.io/part-of: iot-data-generator
  name: iot-data-generator
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/evanshortiss/rhtr-2020-iot-datagen
    from:
      kind: DockerImage
      name: quay.io/evanshortiss/rhtr-2020-iot-datagen
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
