apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: iot-data-generator
    app.kubernetes.io/component: iot-data-generator
    app.kubernetes.io/instance: iot-data-generator
    app.kubernetes.io/name: ""
    app.kubernetes.io/part-of: iot-data-generator
    app.openshift.io/runtime: ""
    app.openshift.io/runtime-version: latest
  name: iot-data-generator
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: iot-data-generator
    deploymentconfig: iot-data-generator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
