# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sensor Management UI CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'services/sensor-management-ui/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'services/sensor-management-ui/**'
defaults:
  run:
    working-directory: 'services/sensor-management-ui/'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - working-directory:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: IOT_GRAPHQL_HOST=http://stub.hostname/graphql GOOGLE_MAPS_API_KEY=stubapikey npm run build
